# Site settings
# these variables can be touched by {{ site.var-name }}
title: MathWiki
email: mathwiki@163.com
description: >- # this means to ignore newlines until "baseurl:"
  致力于成为最好用的高数参考手册，部分文章、资源来源于互联网，如有侵权请联系我们删除。
  你也可以为我们贡献你的精彩见解。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_app: https://github.com/dexfire/mathwiki
github_wiki: https://github.com/dexfire/mathwiki_jekyll
github_jekyll:  https://github.com/jekyllrb

# Build settings

#使用kramdown版本的markwodn语法
markdown: kramdown

#不使用jekyll主题，影响自定义页面的生成
#theme: minima

#Markdown细节配置
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - robots.txt
  - .idea/
  - .gitignore
  - .git/
  
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# 一些文件的默认选项
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
      sidebar: home_sidebar
      